movie_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'movie_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^movielib/', include('movielib.urls', namespace='movielib')),

)

movielib/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from movielib import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create/$', views.CreateView.as_view(), name='create'), 
    url(r'^edit/(?P<pk>\d+)$', views.UpdateView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', views.DeleteView.as_view(), name='movie_delete'),

    
)

movielib/models.py
from django.db import models





class Movie(models.Model):
    title = models.CharField(max_length=255)
    genre = models.CharField(max_length=128)
    release_date = models.DateField()
    price = models.DecimalField(max_digits=20, decimal_places=0)

movielib/forms.py
from movielib.models import Movie 


class MovieMixin(object):
	model = Movie

	def get_context_data(self,**kwargs):
		kwargs.update({'object_name':'Movie'})
		return kwargs

		

movielib/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from movielib.models import Movie 
from movielib.forms import MovieMixin





class IndexView(ListView):
	template_name = 'index.html'
	model = Movie




class CreateView(CreateView):
	template_name= 'create.html'
	model = Movie
	success_url = '/movielib'



class UpdateView(UpdateView):
    template_name = 'update.html'
    model = Movie
    success_url = '/movielib'



class DeleteView(MovieMixin, DeleteView):
	template_name = 'confirm_delete.html'
	model = Movie
	success_url = '/movielib'

movielib/templates/base_page.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>   
    <title>Movie Library - {% block title %}{% endblock %}</title>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> -->
    <link href="{% static "bootstrap.min.css" %}" rel="stylesheet">    
    <link href="{% static "site.css" %}" rel="stylesheet">    

</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">MOVIE LIBRARY</a>
            </div>
            <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'movielib:index' %}">HOME</a></li>
                <li><a href="{% url 'movielib:create' %}">Create</a></li>
            </ul>
            </div>
        </div>
    </div>

    <div class="container">

        <div class="starter-template">
        {% block content %}

        {% endblock %}
        </div>

    </div>
</body>
</html>

movielib/templates/confirm_delete.html
{% extends "base_page.html"%}
{% block content %}
<form method="post">{% csrf_token %}
    <h1> Are you sure you want to delete? </h1> <blockquote>{{ object.title }}</blockquote> 
    <input type="submit" class="btn btn-danger" value="YES" /> <a href="{% url 'movielib:index' %}" class="btn btn-default">NO</a>

</form>
{% endblock %}

movielib/templates/create.html
{% extends "base_page.html" %}

{% block title %}Create Movie{% endblock %}

{% block content %}
<h1>Create Movie</h1>
<form method="post" class="form">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
        </div>
    {% endfor %}
    <input type="submit" value="Submit" />
</form>
{% endblock %}   

movielib/templates/index.html
{% extends "base_page.html" %}

{% block title %}
Movie Library 

{% endblock %}


{% block content %}
<h1>Welcome to Movie Library Application made by Django 1.7 </h1>
<p>Lets have some good time with us.....</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Genre</th>
        <th>Price($)</th>
        <th>Release Date</th>
        <th></th>
    </tr>
    {% for movie in object_list %}
        <tr>
            <td>{{ movie.title }}</td>
            <td>{{ movie.genre }}</td>
            <td>{{ movie.price }}</td>
            <td>{{ movie.release_date }}</td>
            <td>
            	<a href="{% url 'movielib:create' %}" class="btn btn-default">ADD</a>
				<a href="{% url 'movielib:edit' movie.id %}" class="btn btn-default">Edit</a>
                <a href="{% url 'movielib:movie_delete' movie.id %}" class="btn btn-danger">Delete</a>
				</td>
        </tr>
    {% endfor %}
</table>

{% endblock %}

movielib/templates/update.html
{% extends "base_page.html" %}

{% block title %}Update Movie{% endblock %}

{% block content %}
<h1>Update Movie</h1>
<form method="post" class="form">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
        {{ field.errors }}
        {{ field.label_tag }}
        {{ field }}
        </div>
    {% endfor %}
    <input type="submit" value="Submit" />
</form>
{% endblock %}